steps:
  - name: gradle:jdk17-alpine
    entrypoint: gradle
    args: ["assemble"]
    env:
    - 'BUILD=$BUILD_ID'
    - 'COMMIT=$COMMIT_SHA'
 
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/projectk-368003/my-image/myimage-$COMMIT_SHA',
    '-t','gcr.io/projectk-368003/my-image/myimage:latest',
    '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/projectk-368003/my-image/myimage:latest']