steps:
  - name: gradle:jdk17-alpine
    entrypoint: gradle
    args: ["assemble"]
    env:
    - 'BUILD=$BUILD_ID'
    - 'COMMIT=$COMMIT_SHA'
 
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/projectk-368003/my-image/myimage',
    '-t','gcr.io/projectk-368003/my-image/myimage:latest',
    '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/projectk-368003/my-image/myimage:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'Hello', '--image', 'gcr.io/projectk-368003/my-image/myimage:latest', '--region', 'us-central1']